# -*- coding: utf-8 -*-
"""NLP5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13XbYiDmEHkKNazYBVZtH6kIWScTvnvEZ
"""

# -*- coding: utf-8 -*-
"""Класифікація стилів мистецтва: Zero-Shot та Fine-Tuning

Цей код виконує дві задачі:
1. Zero-Shot оцінка моделі CLIP на датасеті WikiArt
2. Fine-Tuning моделі для покращення класифікації

Використовується CLIP та WikiArt dataset з логікою завантаження з першого коду
"""

# Встановлення необхідних бібліотек
!pip install -q datasets transformers torch scikit-learn tqdm matplotlib pillow

import os
import torch
import numpy as np
from datasets import load_dataset
from transformers import CLIPProcessor, CLIPModel
from PIL import Image
import gc
import random
import matplotlib.pyplot as plt
from tqdm.auto import tqdm
from sklearn.metrics import precision_recall_fscore_support, accuracy_score

# Для відтворюваності результатів
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

# Визначення стилів із детальними описами для кожного
STYLE_NAMES = {
    0: "Abstract_Expressionism",
    1: "Action_painting",
    2: "Analytical_Cubism",
    3: "Art_Nouveau",
    4: "Baroque",
    5: "Color_Field_Painting",
    6: "Contemporary_Realism",
    7: "Cubism",
    8: "Early_Renaissance",
    9: "Expressionism",
    10: "Fauvism",
    11: "High_Renaissance",
    12: "Impressionism",
    13: "Mannerism_Late_Renaissance",
    14: "Minimalism",
    15: "Naive_Art_Primitivism",
    16: "New_Realism",
    17: "Northern_Renaissance",
    18: "Pointillism",
    19: "Pop_Art",
    20: "Post_Impressionism",
    21: "Realism",
    22: "Rococo",
    23: "Romanticism",
    24: "Symbolism",
    25: "Synthetic_Cubism",
    26: "Ukiyo_e"
}

# Детальні описи для вибраних стилів
STYLE_DESCRIPTIONS = {
    4: [  # Baroque
        "A painting with dramatic lighting and intense emotions.",
        "A Baroque artwork with rich colors and ornate details.",
        "A painting with dynamic compositions and dramatic contrasts of light and shadow.",
        "An artwork that portrays grandeur, drama, and emotional exuberance.",
        "A painting with elaborate decorative elements and theatrical compositions."
    ],
    12: [  # Impressionism
        "A painting with visible brushstrokes and emphasis on light.",
        "An Impressionist artwork with vibrant colors and outdoor scenes.",
        "A painting that captures fleeting moments of light and atmosphere.",
        "An artwork focused on depicting the visual impression of a scene.",
        "A painting with a sense of movement and light reflecting off objects."
    ],
    20: [  # Post Impressionism
        "A painting with bold colors and distinctive brushwork.",
        "A Post-Impressionist artwork with emotional impact and symbolic content.",
        "A painting that extends Impressionism with more structured forms.",
        "An artwork with distorted forms for expressive effect.",
        "A painting that emphasizes geometric forms and psychological elements."
    ],
    21: [  # Realism
        "A painting depicting everyday life with accuracy and detail.",
        "A Realist artwork showing ordinary people and situations.",
        "A painting that represents actual appearances without idealization.",
        "An artwork portraying contemporary life and social conditions.",
        "A painting with careful observation of real-world scenes and experiences."
    ],
    23: [  # Romanticism
        "A painting emphasizing emotion, imagination, and individualism.",
        "A Romantic artwork with sublime landscapes and dramatic scenes.",
        "A painting that portrays heightened emotional states and natural beauty.",
        "An artwork celebrating nature, passion, and human expression.",
        "A painting with dramatic colors and compositions evoking strong feelings."
    ]
}

# Вибираємо стилі для тестування
SELECTED_STYLES = [4, 12, 20, 21, 23]  # Baroque, Impressionism, Post_Impressionism, Realism, Romanticism
SELECTED_STYLE_NAMES = {k: STYLE_NAMES[k] for k in SELECTED_STYLES}

# Функція для завантаження та підготовки даних (використовуємо логіку з першого коду)
def load_wikiart_data(selected_styles=None, max_samples_per_style=30):
    """
    Завантажує дані WikiArt з використанням streaming та фільтрує за вибраними стилями
    """
    # Завантаження датасету з використанням streaming як у першому коді
    dataset = load_dataset("huggan/wikiart", streaming=True)

    if selected_styles:
        # Збираємо зображення для кожного стилю
        samples_by_style = {}

        # Обмежуємо загальну кількість зразків для перегляду
        MAX_SAMPLES = 1000
        counter = 0

        # Проходимо через потік даних та збираємо зразки
        for sample in dataset['train']:
            if counter >= MAX_SAMPLES:
                break

            style = sample['style']
            image = sample['image']

            # Пропускаємо стилі, які не входять до вибраних
            if style not in selected_styles:
                continue

            if style not in samples_by_style:
                samples_by_style[style] = []

            # Додаємо зразок, якщо ще не досягли ліміту для цього стилю
            if len(samples_by_style[style]) < max_samples_per_style:
                # Зберігаємо тільки потрібні дані
                sample_data = {
                    "image": image,
                    "style": style,
                    "title": sample.get("title", "Unknown"),
                    "author": sample.get("author", "Unknown")
                }
                samples_by_style[style].append(sample_data)

            counter += 1

        # Створюємо збалансовані набори для навчання та тестування
        train_data = []
        test_data = []

        for style in selected_styles:
            if style in samples_by_style:
                style_samples = samples_by_style[style]
                random.shuffle(style_samples)

                # Розділяємо дані: 80% на навчання, 20% на тестування
                split_idx = int(0.8 * len(style_samples))
                train_data.extend(style_samples[:split_idx])
                test_data.extend(style_samples[split_idx:])

        # Перемішуємо дані для уникнення послідовностей одного стилю
        random.shuffle(train_data)
        random.shuffle(test_data)

        print(f"Зібрано {len(train_data)} зразків для навчання")
        print(f"Зібрано {len(test_data)} зразків для тестування")

        return train_data, test_data

    # Якщо стилі не вказані, збираємо всі дані (не рекомендується через розмір датасету)
    print("Увага: збір всіх даних без фільтрації може зайняти багато часу і пам'яті")
    return None, None

# Частина 1: Zero-Shot оцінка використовуючи CLIP
def run_zero_shot_evaluation_clip(test_data, model_name="openai/clip-vit-base-patch32"):
    """
    Виконує Zero-Shot оцінку моделі CLIP на тестових даних з використанням розширених підказок
    """
    print("Запуск Zero-Shot оцінки з CLIP...")

    # Завантаження моделі та процесора
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Використовується пристрій: {device}")

    # Завантаження моделі CLIP
    processor = CLIPProcessor.from_pretrained(model_name)
    model = CLIPModel.from_pretrained(model_name).to(device)

    # Встановлюємо режим оцінки і відключаємо градієнти
    model.eval()
    torch.set_grad_enabled(False)

    # Збір передбачень
    y_true = []
    y_pred = []
    style_predictions = {style: {"correct": 0, "total": 0} for style in SELECTED_STYLES}

    # Обробка тестових даних
    for i, sample in enumerate(tqdm(test_data, desc="Zero-Shot оцінка")):
        if i >= 50:  # Обмежуємо кількість зразків для тестування
            break

        image = sample["image"]
        true_style = sample["style"]

        # Переконуємося, що зображення має правильний формат
        if not isinstance(image, Image.Image):
            print(f"Помилка: отримано {type(image)} замість Image")
            continue

        # Нормалізуємо зображення
        image = image.convert('RGB')

        y_true.append(true_style)
        style_predictions[true_style]["total"] += 1

        # Підготовка текстових підказок з детальними описами
        all_texts = []
        style_indices = {}
        current_idx = 0

        for style_id in SELECTED_STYLES:
            style_indices[style_id] = []

            # Використовуємо більш детальні підказки
            if style_id in STYLE_DESCRIPTIONS:
                for prompt in STYLE_DESCRIPTIONS[style_id]:
                    all_texts.append(prompt)
                    style_indices[style_id].append(current_idx)
                    current_idx += 1
            else:
                # Якщо немає детальних описів, використовуємо базову підказку
                prompt = f"A painting in the {STYLE_NAMES[style_id]} style."
                all_texts.append(prompt)
                style_indices[style_id].append(current_idx)
                current_idx += 1

        # Обробка зображення з усіма підказками
        inputs = processor(
            text=all_texts,
            images=[image] * len(all_texts),
            return_tensors="pt",
            padding=True,
        ).to(device)

        # Отримуємо прогнози
        with torch.no_grad():
            outputs = model(**inputs)

            # Отримуємо ембедінги
            image_embeds = outputs.image_embeds
            text_embeds = outputs.text_embeds

            # Нормалізуємо ембедінги
            image_embeds = image_embeds / image_embeds.norm(dim=-1, keepdim=True)
            text_embeds = text_embeds / text_embeds.norm(dim=-1, keepdim=True)

            # Обчислюємо схожість (cosine similarity)
            similarity = torch.matmul(image_embeds, text_embeds.t())

            # Агрегуємо результати за стилями
            style_scores = {}
            for style_id in SELECTED_STYLES:
                indices = style_indices[style_id]
                style_scores[style_id] = similarity[0, indices].mean().item()

        # Визначаємо стиль з найкращим показником
        predicted_style = max(style_scores.items(), key=lambda x: x[1])[0]
        y_pred.append(predicted_style)

        # Оновлюємо статистику для кожного стилю
        if predicted_style == true_style:
            style_predictions[true_style]["correct"] += 1

        # Виводимо інформацію про зразок
        if True:
            print(f"\nЗразок {i+1}/{min(len(test_data), 50)}")
            print(f"Справжній стиль: {STYLE_NAMES[true_style]}")
            print(f"Передбачений стиль: {STYLE_NAMES[predicted_style]}")
            # Виводимо топ-3 scores
            sorted_scores = sorted(style_scores.items(), key=lambda x: x[1], reverse=True)[:3]
            print("Топ-3 scores:", ", ".join([f"{STYLE_NAMES[s]}: {score:.4f}" for s, score in sorted_scores]))

        # Звільняємо пам'ять
        del inputs, outputs, image_embeds, text_embeds, similarity
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # Оцінка метрик
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average='weighted'
    )
    accuracy = accuracy_score(y_true, y_pred)

    # Виведення результатів
    print(f"\nРезультати Zero-Shot оцінки CLIP на {len(y_true)} зразках:")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")

    # Виведення результатів для кожного стилю
    print("\nРезультати за стилями:")
    for style_id in SELECTED_STYLES:
        correct = style_predictions[style_id]["correct"]
        total = style_predictions[style_id]["total"]
        accuracy_style = correct / total if total > 0 else 0
        print(f"{STYLE_NAMES[style_id]}: {accuracy_style:.4f} ({correct}/{total})")

    # Створення матриці плутанини
    cm = confusion_matrix_for_styles(y_true, y_pred, SELECTED_STYLES)

    # Повертаємо метрики та передбачення для подальшого аналізу
    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "predictions": {
            "y_true": y_true,
            "y_pred": y_pred
        },
        "confusion_matrix": cm
    }

# Функція для створення матриці плутанини
def confusion_matrix_for_styles(y_true, y_pred, selected_styles):
    """
    Створює матрицю плутанини для стилів
    """
    cm = {}
    for t_style in selected_styles:
        cm[t_style] = {}
        for p_style in selected_styles:
            cm[t_style][p_style] = sum(1 for t, p in zip(y_true, y_pred)
                                     if t == t_style and p == p_style)

    # Виведення матриці плутанини в консоль
    print("\nМатриця плутанини:")
    header = "\t" + "\t".join([str(s) for s in selected_styles])
    print(header)

    for t_style in selected_styles:
        row = f"{t_style}"
        for p_style in selected_styles:
            row += f"\t{cm[t_style][p_style]}"
        print(row)

    return cm

# Функція для навчання моделі CLIP для класифікації стилів
def fine_tune_clip(train_data, test_data, model_name="openai/clip-vit-base-patch32", num_epochs=3):
    """
    Виконує Fine-Tuning моделі CLIP на навчальних даних для класифікації стилів мистецтва
    Заморожує більшість шарів і тренує лише останні для адаптації до нових даних
    """
    print("Запуск Fine-Tuning CLIP...")

    # Завантаження моделі та процесора
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Використовується пристрій: {device}")

    # Завантаження моделі CLIP
    processor = CLIPProcessor.from_pretrained(model_name)
    model = CLIPModel.from_pretrained(model_name).to(device)

    # Важливо: заморозити більшість моделі і розморозити тільки фінальні шари
    for param in model.parameters():
        param.requires_grad = False

    # Розморожуємо тільки останні шари візуальної та текстової частин
    # Візуальна частина
    for param in model.vision_model.encoder.layers[-1].parameters():
        param.requires_grad = True

    # Текстова частина
    for param in model.text_model.encoder.layers[-1].parameters():
        param.requires_grad = True

    # Також розморозимо проекційні шари та logit_scale
    for param in model.visual_projection.parameters():
        param.requires_grad = True
    for param in model.text_projection.parameters():
        param.requires_grad = True
    model.logit_scale.requires_grad = True

    # Переключаємо модель в режим навчання
    model.train()

    # Виводимо кількість параметрів, які будуть тренуватися
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())
    print(f"Параметрів для тренування: {trainable_params:,} з {total_params:,} ({trainable_params/total_params*100:.2f}%)")

    # Створюємо оптимізатор тільки для параметрів, які потребують навчання
    optimizer = torch.optim.AdamW(
        [p for p in model.parameters() if p.requires_grad],
        lr=1e-5,  # Трохи підвищений learning rate для обмеженої кількості параметрів
        weight_decay=0.01
    )

    # Підготовка даних для навчання
    batch_size = 4  # Підберіть відповідно до доступної пам'яті GPU

    # Обмежуємо розмір навчального набору для демонстрації
    max_train_samples = min(len(train_data), 120)
    train_samples = train_data[:max_train_samples]

    # Функція для створення батчів
    def create_batches(samples, batch_size):
        """Створює пакети для навчання"""
        random.shuffle(samples)  # Перемішуємо дані
        num_batches = len(samples) // batch_size
        batches = []

        for i in range(num_batches):
            start_idx = i * batch_size
            end_idx = start_idx + batch_size
            batches.append(samples[start_idx:end_idx])

        # Додаємо останній неповний пакет, якщо такий є
        if len(samples) % batch_size != 0:
            batches.append(samples[num_batches * batch_size:])

        return batches

    # Відстежуємо загальну втрату для візуалізації
    epoch_losses = []

    for epoch in range(num_epochs):
        # Створюємо нові батчі для кожної епохи
        train_batches = create_batches(train_samples, batch_size)
        epoch_loss = 0

        for batch_idx, batch in enumerate(tqdm(train_batches, desc=f"Епоха {epoch+1}/{num_epochs}")):
            # Важливо: обнуляємо градієнти перед кожним кроком
            optimizer.zero_grad()

            # Підготовка зображень та цільових стилів
            images = [sample["image"].convert("RGB") for sample in batch]
            styles = [sample["style"] for sample in batch]

            # Створюємо текстові підказки для кожного стилю в пакеті
            texts = [f"A painting in the {STYLE_NAMES[style]} style." for style in styles]

            # Обробка зображень та текстів
            with torch.set_grad_enabled(True):  # Важливо: явно включаємо відстеження градієнтів
                inputs = processor(
                    text=texts,
                    images=images,
                    return_tensors="pt",
                    padding=True,
                ).to(device)

                # Отримуємо вихідні дані моделі
                outputs = model(**inputs)

                # Отримуємо ембедінги
                image_embeds = outputs.image_embeds
                text_embeds = outputs.text_embeds

                # Нормалізуємо ембедінги
                image_embeds = image_embeds / image_embeds.norm(dim=-1, keepdim=True)
                text_embeds = text_embeds / text_embeds.norm(dim=-1, keepdim=True)

                # Обчислюємо матрицю схожості з правильним масштабуванням
                logit_scale = model.logit_scale.exp()
                logits = torch.matmul(image_embeds, text_embeds.t()) * logit_scale

                # Створюємо цільові мітки: кожне зображення повинно відповідати своєму тексту
                labels = torch.arange(len(batch)).to(device)

                # Обчислюємо втрату
                loss_fct = torch.nn.CrossEntropyLoss()
                loss_i2t = loss_fct(logits, labels)
                loss_t2i = loss_fct(logits.t(), labels)
                loss = (loss_i2t + loss_t2i) / 2

                # Зворотне поширення
                loss.backward()

                # Оновлення ваг
                optimizer.step()

            # Відстежуємо втрату
            epoch_loss += loss.item()

            # Логуємо прогрес
            if batch_idx % 5 == 0:
                print(f"Пакет {batch_idx+1}/{len(train_batches)}, Втрата: {loss.item():.6f}")

            # Звільняємо пам'ять
            del inputs, outputs, image_embeds, text_embeds, logits, loss, loss_i2t, loss_t2i
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

        # Обчислюємо середню втрату за епоху
        avg_epoch_loss = epoch_loss / len(train_batches)
        epoch_losses.append(avg_epoch_loss)

        print(f"Епоха {epoch+1}/{num_epochs}, Середня втрата: {avg_epoch_loss:.6f}")

    # Зберігаємо модель
    output_dir = "./fine_tuned_clip"
    os.makedirs(output_dir, exist_ok=True)
    model.save_pretrained(output_dir)
    processor.save_pretrained(output_dir)

    print(f"Модель збережено в {output_dir}")

    # Візуалізуємо втрати навчання
    plt.figure(figsize=(10, 6))
    plt.plot(range(1, num_epochs+1), epoch_losses, marker='o')
    plt.title('Втрати навчання за епохами')
    plt.xlabel('Епоха')
    plt.ylabel('Середня втрата')
    plt.grid(True)
    plt.savefig('training_loss.png')
    plt.close()

    # Оцінка навченої моделі
    print("\nОцінка fine-tuned моделі...")

    # Переключаємо модель в режим оцінки
    model.eval()
    torch.set_grad_enabled(False)

    # Обмежуємо кількість тестових зразків
    max_test_samples = min(len(test_data), 50)
    test_samples = test_data[:max_test_samples]

    # Збір передбачень
    y_true = []
    y_pred = []
    style_predictions = {style: {"correct": 0, "total": 0} for style in SELECTED_STYLES}

    # Обробка тестових даних
    for i, sample in enumerate(tqdm(test_samples, desc="Оцінка fine-tuned моделі")):
        image = sample["image"]
        true_style = sample["style"]

        # Переконуємося, що зображення має правильний формат
        if not isinstance(image, Image.Image):
            print(f"Помилка: отримано {type(image)} замість Image")
            continue

        # Нормалізуємо зображення
        image = image.convert('RGB')

        y_true.append(true_style)
        style_predictions[true_style]["total"] += 1

        # Підготовка текстових підказок для всіх стилів
        all_texts = [f"A painting in the {STYLE_NAMES[style_id]} style." for style_id in SELECTED_STYLES]

        # Обробка зображення з усіма підказками
        inputs = processor(
            text=all_texts,
            images=[image] * len(all_texts),
            return_tensors="pt",
            padding=True,
        ).to(device)

        # Отримуємо прогнози
        with torch.no_grad():
            outputs = model(**inputs)

            # Отримуємо ембедінги
            image_embeds = outputs.image_embeds
            text_embeds = outputs.text_embeds

            # Нормалізуємо ембедінги
            image_embeds = image_embeds / image_embeds.norm(dim=-1, keepdim=True)
            text_embeds = text_embeds / text_embeds.norm(dim=-1, keepdim=True)

            # Обчислюємо схожість
            similarity = torch.matmul(image_embeds, text_embeds.t())

            # Отримуємо індекс стилю з найвищою схожістю
            max_idx = similarity.argmax().item()
            predicted_style = SELECTED_STYLES[max_idx]

        y_pred.append(predicted_style)

        # Оновлюємо статистику для кожного стилю
        if predicted_style == true_style:
            style_predictions[true_style]["correct"] += 1

        # Виводимо інформацію про зразок
        if True:
            print(f"\nЗразок {i+1}/{len(test_samples)}")
            print(f"Справжній стиль: {STYLE_NAMES[true_style]}")
            print(f"Передбачений стиль: {STYLE_NAMES[predicted_style]}")

            # Виводимо scores для всіх стилів
            scores = similarity[0].tolist()
            style_scores = {SELECTED_STYLES[i]: scores[i] for i in range(len(SELECTED_STYLES))}
            sorted_scores = sorted(style_scores.items(), key=lambda x: x[1], reverse=True)
            print("Всі scores:", ", ".join([f"{STYLE_NAMES[s]}: {score:.4f}" for s, score in sorted_scores]))

        # Звільняємо пам'ять
        del inputs, outputs, image_embeds, text_embeds, similarity
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # Оцінка метрик
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average='weighted'
    )
    accuracy = accuracy_score(y_true, y_pred)

    # Виведення результатів
    print(f"\nРезультати оцінки fine-tuned моделі на {len(y_true)} зразках:")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")

    # Виведення результатів для кожного стилю
    print("\nРезультати за стилями:")
    for style_id in SELECTED_STYLES:
        correct = style_predictions[style_id]["correct"]
        total = style_predictions[style_id]["total"]
        accuracy_style = correct / total if total > 0 else 0
        print(f"{STYLE_NAMES[style_id]}: {accuracy_style:.4f} ({correct}/{total})")

    # Створення матриці плутанини
    cm = confusion_matrix_for_styles(y_true, y_pred, SELECTED_STYLES)

    # Повертаємо метрики та передбачення для порівняння
    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "predictions": {
            "y_true": y_true,
            "y_pred": y_pred
        },
        "confusion_matrix": cm
    }

def plot_comparison(zero_shot_metrics, fine_tuned_metrics):
    """
    Візуалізує порівняння метрик zero-shot та fine-tuned моделей
    """
    metrics = ["accuracy", "precision", "recall", "f1"]
    zero_shot_values = [zero_shot_metrics[m] for m in metrics]
    fine_tuned_values = [fine_tuned_metrics[m] for m in metrics]

    x = np.arange(len(metrics))
    width = 0.35

    fig, ax = plt.subplots(figsize=(10, 6))
    rects1 = ax.bar(x - width/2, zero_shot_values, width, label='Zero-Shot CLIP')
    rects2 = ax.bar(x + width/2, fine_tuned_values, width, label='Fine-Tuned CLIP')

    ax.set_ylabel('Значення')
    ax.set_title('Порівняння Zero-Shot та Fine-Tuned метрик')
    ax.set_xticks(x)
    ax.set_xticklabels(metrics)
    ax.legend()

    ax.set_ylim(0, 1.0)

    def autolabel(rects):
        for rect in rects:
            height = rect.get_height()
            ax.annotate(f'{height:.4f}',
                        xy=(rect.get_x() + rect.get_width() / 2, height),
                        xytext=(0, 3),
                        textcoords="offset points",
                        ha='center', va='bottom')

    autolabel(rects1)
    autolabel(rects2)

    fig.tight_layout()
    plt.savefig('comparison_metrics.png')
    plt.show()

# Головна функція
def main():
    # Завантаження даних WikiArt зі streaming
    train_data, test_data = load_wikiart_data(SELECTED_STYLES, max_samples_per_style=30)

    # Виконання Zero-Shot оцінки з CLIP
    zero_shot_metrics = run_zero_shot_evaluation_clip(test_data)

    # Виконання Fine-Tuning CLIP
    fine_tuned_metrics = fine_tune_clip(train_data, test_data, num_epochs=3)

    # Порівняння результатів
    plot_comparison(zero_shot_metrics, fine_tuned_metrics)

    print("\n======= Порівняння результатів =======")
    print("Метрика\t\tZero-Shot\tFine-Tuned\tПокращення")
    for metric in ["accuracy", "precision", "recall", "f1"]:
        improvement = fine_tuned_metrics[metric] - zero_shot_metrics[metric]
        print(f"{metric.capitalize()}\t{zero_shot_metrics[metric]:.4f}\t{fine_tuned_metrics[metric]:.4f}\t{improvement:+.4f}")

if __name__ == "__main__":
    main()