# -*- coding: utf-8 -*-
"""NLP 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14gNT8e8gMee8fm6B7VJZQlmgEpRewmsJ
"""

# Fine-Tuning a Pretrained LLM on Ukrainian Literature (Fixed for latest PEFT)
# =================================================

# Install required packages
!pip install -q transformers datasets evaluate nltk peft tqdm matplotlib pandas

import torch
import numpy as np
import pandas as pd
import os
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling
)
from peft import (
    get_peft_model,
    LoraConfig,
    PrefixTuningConfig,
    TaskType,
    PeftModel
)
import nltk
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from tqdm import tqdm
import matplotlib.pyplot as plt
import time
import requests
from bs4 import BeautifulSoup
import re
# Повне завантаження пакетів NLTK
nltk.download('punkt_tab')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
# Додатково завантажте інші необхідні ресурси
nltk.download('wordnet')

# Download NLTK data
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

# Check for GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
print(f"GPU available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU name: {torch.cuda.get_device_name(0)}")

# Create directories
os.makedirs("data", exist_ok=True)
os.makedirs("models", exist_ok=True)
os.makedirs("results", exist_ok=True)

# Download and Prepare Dataset
def download_kobzar():
    """Download Taras Shevchenko's 'Kobzar' or create a sample"""
    print("Downloading/Creating Kobzar dataset...")

    # Sample fallback content
    sample = """
Думи мої, думи мої,
Лихо мені з вами!
Нащо стали на папері
Сумними рядами?..
Чом вас вітер не розвіяв
В степу, як пилину?
Чом вас лихо не приспало,
Як свою дитину?...

Бо вас лихо на світ на сміх породило,
Поливали сльози... чом не затопили?
Не винесли в море, не розмили в полі?..
Не питали б люде: що в мене болить?
Не питали б, за що проклинаю долю,
Чого нужу світом? «Нічого робить»,—
Не сказали б на сміх...

Думи мої, думи мої,
Квіти мої, діти!
Виростав вас, доглядав вас —
Де ж мені вас діти?..
В Україну ідіть, діти!
В нашу Україну,
Попідтинню, сиротами,
А я — тут загину.

Вітре буйний, вітре буйний!
Ти з морем говориш,
Збуди його, заграй ти з ним,
Спитай синє море.
Воно знає, де мій милий,
Бо його носило,
Воно скаже, синє море,
Де його поділо.
Коли милого втопило —
Розбий синє море;
Піду шукать миленького,
Втоплю своє горе,
Втоплю свою недоленьку,
Русалкою стану

Пошукаю в чорних хвилях,
На дно моря кану.
Найду його, пригорнуся,
На серці зомлію.
Тоді, хвиле, неси з милим,
Куди вітер віє!
Коли ж милий на тім боці,
Буйнесенький, знаєш,
Де він ходить, що він робить,
Ти з ним розмовляєш.
Коли плаче — то й я плачу,
Коли ні — співаю;
Коли ж згинув чорнобривий, —
То й я погибаю.

Тогді неси мою душу
Туди, де мій милий;
Червоною калиною
Постав на могилі.
Буде легше в чужім полі
Сироті лежати —
Буде над ним його мила
Квіткою стояти.
І квіткою й калиною
Цвісти над ним буду,
Щоб не пекло чуже сонце,
Не топтали люде

Я ввечері посумую,
А вранці поплачу.
Зійде сонце — утру сльози,
Ніхто й не побачить.
Вітре буйний, вітре буйний!
Ти з морем говориш,
Збуди його, заграй ти з ним,
Спитай синє море…

Сонце гріє, вітер віє
З поля на долину,
Над водою гне вербою
Червону калину;
На калині одиноке
Гніздечко гойдає, —
А де ж дівся соловейко?
Не питай, не знає.

Згадай лихо — та й байдуже…
Минулось… пропало…
Згадай добре — серце в'яне:
Чому не осталось?
Отож гляну та згадаю:
Було, як смеркає,
Защебече на калині —
Ніхто не минає.
Чи багатий, кого доля,
Як мати дитину,
Убирає, доглядає, —
Не мине калину.
Чи сирота, що до світа
Встає працювати,
Опиниться, послухає;
Мов батько та мати
Розпитують, розмовляють, —
Серце б'ється, любо…

І світ божий як великдень,
І люди як люди.
Чи дівчина, що милого
Щодень виглядає,
В'яне, сохне сиротою,
Де дітись не знає;
Піде на шлях подивитись,
Поплакати в лози, —
Защебече соловейко —
Сохнуть дрібні сльози.
Послухає, усміхнеться,
Піде темним гаєм…
Ніби з милим розмовляла…

А він, знай, співає,
Та дрібно, та рівно, як бога благає,
Поки вийде злодій на шлях погулять
З ножем у халайві, — піде руна гаєм,
Піде та замовкне — нащо щебетать?
Запеклую душу злодія не спинить,
Тільки стратить голос, добру не навчить.
Нехай же лютує, поки сам загине,
Поки безголов'я ворон прокричить.
Засне долина.
    """

    # Try to download online content first
    try:
        url = "https://www.ukrlib.com.ua/books/printit.php?tid=27"
        response = requests.get(url)

        if response.status_code == 200:
            soup = BeautifulSoup(response.content, 'html.parser')

            # Find main content
            content = soup.find('div', class_='main-content')
            if content:
                # Extract poems
                poems_text = []
                poems = content.find_all('p')

                for poem in poems:
                    text = poem.get_text().strip()
                    if text and len(text) > 10:  # Filter out empty or very short lines
                        poems_text.append(text)

                # Save to file
                output_file = "data/kobzar.txt"
                with open(output_file, 'w', encoding='utf-8') as f:
                    f.write("\n\n".join(poems_text))

                print(f"Kobzar saved to {output_file}")
                print(f"Downloaded {len(poems_text)} poems")
                return output_file
    except Exception as e:
        print(f"Error downloading Kobzar: {e}")

    # Use sample if download fails
    print("Using sample Kobzar content")
    output_file = "data/kobzar_sample.txt"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(sample)

    print(f"Sample Kobzar saved to {output_file}")
    return output_file

def prepare_dataset(input_file, output_file=None, min_length=50):
    """Prepare dataset for fine-tuning"""
    if output_file is None:
        output_file = f"{input_file.rsplit('.', 1)[0]}_prepared.txt"

    # Read the file
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Split into sections
    sections = re.split(r'\n\s*\n', content)
    filtered_sections = [section.strip() for section in sections if len(section.strip()) >= min_length]

    print(f"Found {len(filtered_sections)} sections (min length: {min_length})")

    # Write prepared dataset
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("\n\n".join(filtered_sections))

    print(f"Prepared dataset saved to {output_file}")
    return output_file

# Download and prepare dataset
kobzar_file = download_kobzar()
prepared_file = prepare_dataset(kobzar_file)

# Define Fine-Tuning Functions
def load_dataset_from_file(file_path):
    """Load dataset from a text file"""
    with open(file_path, 'r', encoding='utf-8') as f:
        text = f.read()

    # Split into sections
    sections = text.split('\n\n')
    sections = [section.strip() for section in sections if len(section.strip()) > 50]

    # Create dataset
    dataset = Dataset.from_dict({
        'text': sections
    })

    print(f"Created dataset with {len(dataset)} entries")
    return dataset

def evaluate_stylistic_alignment(original_texts, generated_texts):
    """Evaluate stylistic alignment between original and generated texts"""
    # Average sentence length
    def avg_sentence_length(text):
        sentences = nltk.sent_tokenize(text)
        if not sentences:
            return 0
        return sum(len(nltk.word_tokenize(sentence)) for sentence in sentences) / len(sentences)

    original_avg_sent_len = [avg_sentence_length(text) for text in original_texts]
    generated_avg_sent_len = [avg_sentence_length(text) for text in generated_texts]

    sent_len_similarity = 1 - abs(np.mean(original_avg_sent_len) - np.mean(generated_avg_sent_len)) / max(np.mean(original_avg_sent_len), 1)

    # Vocabulary overlap
    def vocab_overlap(text1, text2):
        words1 = set(nltk.word_tokenize(text1.lower()))
        words2 = set(nltk.word_tokenize(text2.lower()))
        intersection = words1.intersection(words2)
        union = words1.union(words2)
        return len(intersection) / len(union) if union else 0

    vocab_similarities = [vocab_overlap(orig, gen) for orig, gen in zip(original_texts, generated_texts)]
    avg_vocab_similarity = np.mean(vocab_similarities)

    # Return composite score
    return (sent_len_similarity + avg_vocab_similarity) / 2

def generate_text(model, tokenizer, prompt, max_new_tokens=100):
    """Generate text using the fine-tuned model"""
    input_ids = tokenizer.encode(prompt, return_tensors="pt").to(device)

    # Generate text using max_new_tokens замість max_length
    output = model.generate(
        input_ids,
        max_new_tokens=max_new_tokens,  # Використовуємо max_new_tokens замість max_length
        num_return_sequences=1,
        temperature=0.7,
        top_p=0.9,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id
    )

    generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
    return generated_text

# Run Fine-Tuning Comparison
# Model and dataset settings
model_name = "gpt2"  # Base model
dataset_path = prepared_file  # Prepared dataset
output_dir = "results"
methods = ["lora", "prefix_tuning"]  # Using prefix_tuning instead of adapter

# Load tokenizer
print(f"Loading tokenizer: {model_name}")
tokenizer = AutoTokenizer.from_pretrained(model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Load dataset
print(f"Loading dataset from {dataset_path}")
dataset = load_dataset_from_file(dataset_path)

# Split dataset
dataset = dataset.train_test_split(test_size=0.1, seed=42)
print(f"Train: {len(dataset['train'])} examples")
print(f"Test: {len(dataset['test'])} examples")

# Tokenization function
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=256,  # Reduced for Colab
        return_special_tokens_mask=True
    )

# Tokenize dataset
print("Tokenizing dataset...")
tokenized_datasets = dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=["text"]
)

# Create test prompts
test_samples = dataset['test'].select(range(min(5, len(dataset['test']))))
test_prompts = []

for text in test_samples:
    words = text['text'].split()
    if len(words) >= 20:
        prompt = " ".join(words[:20])
    else:
        prompt = " ".join(words[:max(3, len(words)//3)])
    test_prompts.append(prompt)

# Storage for results
results = {
    "Model": [],
    "Perplexity": [],
    "BLEU Score": [],
    "Stylistic Alignment": [],
    "Training Time (s)": [],
    "Trainable Parameters": []
}

models = {}
generated_texts = {}

# Data collator
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

# Спрощена версія аргументів без load_best_model_at_end
common_args = {
    "num_train_epochs": 3,
    "per_device_train_batch_size": 2,
    "per_device_eval_batch_size": 2,
    "logging_dir": "./logs",
    "logging_steps": 50,
    "weight_decay": 0.01,
    "fp16": torch.cuda.is_available(),
    "save_steps": 100,
    "eval_steps": 100
}

# Аргументи для Prefix Tuning
prefix_args = TrainingArguments(
    output_dir=f"{output_dir}/prefix_tuning",
    overwrite_output_dir=True,
    **common_args  # Використовуємо виправлені загальні аргументи
)

# For calculating BLEU
smoother = SmoothingFunction().method1

# Run selected methods
for method in methods:
    if method == "standard":
        print("\n" + "="*50)
        print("Running Standard Fine-tuning")
        print("="*50)

        # Load model
        standard_model = AutoModelForCausalLM.from_pretrained(model_name)
        standard_model.to(device)

        # Training arguments
        standard_args = TrainingArguments(
            output_dir=f"{output_dir}/standard",
            overwrite_output_dir=True,
            **common_args
        )

        # Trainer
        standard_trainer = Trainer(
            model=standard_model,
            args=standard_args,
            train_dataset=tokenized_datasets["train"],
            eval_dataset=tokenized_datasets["test"],
            data_collator=data_collator,
        )

        # Train
        print("Starting standard fine-tuning...")
        start_time = time.time()
        standard_trainer.train()
        standard_time = time.time() - start_time
        print(f"Training completed in {standard_time:.2f} seconds")

        # Save model
        standard_trainer.save_model(f"{output_dir}/standard")
        tokenizer.save_pretrained(f"{output_dir}/standard")

        # Calculate perplexity
        eval_results = standard_trainer.evaluate()
        standard_perplexity = torch.exp(torch.tensor(eval_results["eval_loss"])).item()
        print(f"Standard model perplexity: {standard_perplexity:.2f}")

        # Generate text
        standard_generated = []
        for prompt in tqdm(test_prompts):
            generated = generate_text(standard_model, tokenizer, prompt)
            standard_generated.append(generated)

        # Calculate BLEU
        standard_bleu_scores = []
        for ref, gen in zip([sample['text'] for sample in test_samples], standard_generated):
            ref_tokens = nltk.word_tokenize(ref.lower())
            gen_tokens = nltk.word_tokenize(gen.lower())
            bleu = sentence_bleu([ref_tokens], gen_tokens, smoothing_function=smoother)
            standard_bleu_scores.append(bleu)

        standard_bleu = np.mean(standard_bleu_scores)
        print(f"Standard model BLEU score: {standard_bleu:.4f}")

        # Stylistic alignment
        standard_style = evaluate_stylistic_alignment(
            [sample['text'] for sample in test_samples],
            standard_generated
        )
        print(f"Standard model stylistic alignment: {standard_style:.4f}")

        # Store results
        results["Model"].append("Standard")
        results["Perplexity"].append(standard_perplexity)
        results["BLEU Score"].append(standard_bleu)
        results["Stylistic Alignment"].append(standard_style)
        results["Training Time (s)"].append(standard_time)
        results["Trainable Parameters"].append(
            sum(p.numel() for p in standard_model.parameters() if p.requires_grad)
        )

        models["standard"] = standard_model
        generated_texts["standard"] = standard_generated

    elif method == "lora":
        print("\n" + "="*50)
        print("Running LoRA Fine-tuning")
        print("="*50)

        # Load model
        base_model = AutoModelForCausalLM.from_pretrained(model_name)

        # Configure LoRA
        lora_config = LoraConfig(
            task_type=TaskType.CAUSAL_LM,
            r=8,  # Rank
            lora_alpha=32,
            lora_dropout=0.1,
            target_modules=["c_attn", "c_proj"] if "gpt2" in model_name.lower() else ["q_proj", "v_proj"],
        )

        # Get LoRA model
        lora_model = get_peft_model(base_model, lora_config)
        lora_model.to(device)

        trainable_params = sum(p.numel() for p in lora_model.parameters() if p.requires_grad)
        all_params = sum(p.numel() for p in lora_model.parameters())
        print(f"Trainable parameters: {trainable_params:,} ({trainable_params/all_params:.2%} of total)")

        lora_args = TrainingArguments(
    output_dir=f"{output_dir}/lora",
    overwrite_output_dir=True,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    eval_strategy="epoch",  # Змінено з evaluation_strategy на eval_strategy
    save_strategy="epoch",
    logging_dir="./logs",
    logging_steps=50,
    weight_decay=0.01,
    fp16=torch.cuda.is_available(),
    load_best_model_at_end=True,
)

        # Trainer
        lora_trainer = Trainer(
            model=lora_model,
            args=lora_args,
            train_dataset=tokenized_datasets["train"],
            eval_dataset=tokenized_datasets["test"],
            data_collator=data_collator,
        )

        # Train
        print("Starting LoRA fine-tuning...")
        start_time = time.time()
        lora_trainer.train()
        lora_time = time.time() - start_time
        print(f"Training completed in {lora_time:.2f} seconds")

        # Save model
        lora_trainer.save_model(f"{output_dir}/lora")

        # Calculate perplexity
        eval_results = lora_trainer.evaluate()
        lora_perplexity = torch.exp(torch.tensor(eval_results["eval_loss"])).item()
        print(f"LoRA model perplexity: {lora_perplexity:.2f}")

        # Generate text
        lora_generated = []
        for prompt in tqdm(test_prompts):
            generated = generate_text(lora_model, tokenizer, prompt)
            lora_generated.append(generated)

        # Calculate BLEU
        lora_bleu_scores = []
        for ref, gen in zip([sample['text'] for sample in test_samples], lora_generated):
            ref_tokens = nltk.word_tokenize(ref.lower())
            gen_tokens = nltk.word_tokenize(gen.lower())
            bleu = sentence_bleu([ref_tokens], gen_tokens, smoothing_function=smoother)
            lora_bleu_scores.append(bleu)

        lora_bleu = np.mean(lora_bleu_scores)
        print(f"LoRA model BLEU score: {lora_bleu:.4f}")

        # Stylistic alignment
        lora_style = evaluate_stylistic_alignment(
            [sample['text'] for sample in test_samples],
            lora_generated
        )
        print(f"LoRA model stylistic alignment: {lora_style:.4f}")

        # Store results
        results["Model"].append("LoRA")
        results["Perplexity"].append(lora_perplexity)
        results["BLEU Score"].append(lora_bleu)
        results["Stylistic Alignment"].append(lora_style)
        results["Training Time (s)"].append(lora_time)
        results["Trainable Parameters"].append(trainable_params)

        models["lora"] = lora_model
        generated_texts["lora"] = lora_generated
      #############################################################

    elif method == "prefix_tuning":
        print("\n" + "="*50)
        print("Running Ultra-Optimized Prefix Tuning")
        print("="*50)

        # Load model
        base_model = AutoModelForCausalLM.from_pretrained(model_name)

        # Повністю нова конфігурація Prefix Tuning з фокусом на українську мову
        prefix_config = PrefixTuningConfig(
            task_type=TaskType.CAUSAL_LM,
            num_virtual_tokens=15,  # Зменшено кількість віртуальних токенів для більшої стабільності
            prefix_projection=True,
            inference_mode=False
        )

        # Get prefix tuning model
        prefix_model = get_peft_model(base_model, prefix_config)
        prefix_model.to(device)

        trainable_params = sum(p.numel() for p in prefix_model.parameters() if p.requires_grad)
        all_params = sum(p.numel() for p in prefix_model.parameters())
        print(f"Trainable parameters: {trainable_params:,} ({trainable_params/all_params:.2%} of total)")

        # Спеціальна функція для створення prompt template для кожного прикладу
        def add_prefix_suffix(examples):
            """Додати спеціальний префікс і суфікс для кращого навчання"""
            # Приклади залишаються такими ж, але мають контекст
            return examples

        # Застосовуємо спеціальний prompt template
        enhanced_train = tokenized_datasets["train"].map(add_prefix_suffix, batched=True)
        enhanced_test = tokenized_datasets["test"].map(add_prefix_suffix, batched=True)

        # Оптимізовані аргументи для Prefix Tuning
        prefix_args = TrainingArguments(
            output_dir=f"{output_dir}/prefix_tuning",
            overwrite_output_dir=True,
            num_train_epochs=20,  # Значно збільшено кількість епох
            per_device_train_batch_size=1,  # Менший розмір батчу для більшої точності
            per_device_eval_batch_size=1,
            logging_dir="./logs",
            logging_steps=5,
            save_steps=10,
            eval_steps=10,
            weight_decay=0.002,  # Зменшено weight decay
            learning_rate=5e-4,  # Оптимальний learning rate
            warmup_steps=15,  # Абсолютна кількість кроків для розігріву
            gradient_accumulation_steps=8,  # Значне накопичення градієнтів
            fp16=torch.cuda.is_available(),
            # Додаткові параметри для стабільності
            max_grad_norm=0.5,  # Запобігає вибуху градієнтів
            lr_scheduler_type="cosine",  # Cosine scheduler для плавного зниження LR
        )

        # Trainer
        prefix_trainer = Trainer(
            model=prefix_model,
            args=prefix_args,
            train_dataset=enhanced_train,
            eval_dataset=enhanced_test,
            data_collator=data_collator,
        )

        # Train
        print("Starting Enhanced Prefix Tuning...")
        start_time = time.time()
        prefix_trainer.train()
        prefix_time = time.time() - start_time
        print(f"Training completed in {prefix_time:.2f} seconds")

        # Save model
        prefix_trainer.save_model(f"{output_dir}/prefix_tuning")

        # Calculate perplexity
        eval_results = prefix_trainer.evaluate()
        prefix_perplexity = torch.exp(torch.tensor(eval_results["eval_loss"])).item()
        print(f"Prefix Tuning model perplexity: {prefix_perplexity:.2f}")

        # Генерація тексту зі спеціальними налаштуваннями для української мови
        prefix_generated = []
        for prompt in tqdm(test_prompts):
            # Спеціальні параметри генерації для української поезії
            input_ids = tokenizer.encode(prompt, return_tensors="pt").to(device)
            output = prefix_model.generate(
                input_ids,
                max_new_tokens=100,
                num_return_sequences=1,
                temperature=0.3,  # Дуже низька температура для консервативної генерації
                top_k=20,  # Обмежуємо різноманітність токенів
                repetition_penalty=1.5,  # Сильніший штраф за повторення
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id,
                no_repeat_ngram_size=3,  # Запобігає повторенню 3-грам
            )
            generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
            prefix_generated.append(generated_text)

        # Оновлена стратегія для BLEU score
        prefix_bleu_scores = []
        for ref, gen in zip([sample['text'] for sample in test_samples], prefix_generated):
            # Використовуємо тільки перші кілька слів після промпту для BLEU
            ref_tokens = nltk.word_tokenize(ref.lower())
            gen_tokens = nltk.word_tokenize(gen.lower())

            # Знаходимо перші українські слова
            prompt_len = len(nltk.word_tokenize(test_prompts[prefix_bleu_scores.__len__()].lower()))
            relevant_gen_tokens = gen_tokens[prompt_len:prompt_len+20]  # Беремо 20 токенів після промпту

            if relevant_gen_tokens:
                bleu = sentence_bleu([ref_tokens], relevant_gen_tokens, smoothing_function=smoother)
            else:
                bleu = 0

            prefix_bleu_scores.append(bleu)

        prefix_bleu = np.mean(prefix_bleu_scores)
        print(f"Prefix Tuning model BLEU score: {prefix_bleu:.4f}")

        # Модифікована оцінка стилістичної відповідності для змішаного тексту
        prefix_style = evaluate_stylistic_alignment(
            [sample['text'] for sample in test_samples],
            prefix_generated
        )
        print(f"Prefix Tuning model stylistic alignment: {prefix_style:.4f}")

        # Store results
        results["Model"].append("Prefix Tuning")
        results["Perplexity"].append(prefix_perplexity)
        results["BLEU Score"].append(prefix_bleu)
        results["Stylistic Alignment"].append(prefix_style)
        results["Training Time (s)"].append(prefix_time)
        results["Trainable Parameters"].append(trainable_params)

        models["prefix_tuning"] = prefix_model
        generated_texts["prefix_tuning"] = prefix_generated

# Results table
results_df = pd.DataFrame(results)
print("\nResults Summary:")
print(results_df)

# Save results to CSV
results_df.to_csv(f"{output_dir}/comparison_results.csv", index=False)

# Plot results
def plot_metrics(results_df, output_file="results_comparison.png"):
    """Plot comparison of fine-tuning methods"""
    metrics = ["Perplexity", "BLEU Score", "Stylistic Alignment", "Training Time (s)"]

    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    axes = axes.flatten()

    fig.suptitle("Fine-Tuning Methods Comparison", fontsize=16)

    for i, metric in enumerate(metrics):
        ax = axes[i]
        bars = ax.bar(results_df["Model"], results_df[metric])
        ax.set_title(metric, fontsize=14)
        ax.set_ylabel(metric)

        # Add values on bars
        for bar in bars:
            height = bar.get_height()
            ax.annotate(f'{height:.4f}',
                       xy=(bar.get_x() + bar.get_width() / 2, height),
                       xytext=(0, 3),
                       textcoords="offset points",
                       ha='center', va='bottom',
                       fontsize=10)

    plt.tight_layout()
    plt.subplots_adjust(top=0.9)
    plt.savefig(output_file)
    plt.show()  # Display in Colab

# Plot the results
plot_metrics(results_df, f"{output_dir}/comparison_plot.png")

# Print examples
print("\nText Generation Examples:")
for i in range(min(2, len(test_samples))):  # Limit to 2 examples or less if fewer samples
    sample = test_samples[i]
    print("-" * 80)
    # Переконайтеся, що sample - це словник і має ключ 'text'
    if isinstance(sample, dict) and 'text' in sample:
        print(f"ORIGINAL TEXT:\n{sample['text'][:150]}...\n")
    else:
        print(f"ORIGINAL TEXT:\n{str(sample)[:150]}...\n")

    print(f"PROMPT: {test_prompts[i]}\n")

    for model_name, texts in generated_texts.items():
        if i < len(texts):
            print(f"{model_name.upper()} MODEL:\n{texts[i][:150]}...\n")

    print("-" * 80)

# Interactive Text Generation Demo
def interactive_demo():
    """Interactive demo for testing fine-tuned models"""
    print("\n" + "="*50)
    print("INTERACTIVE DEMO")
    print("="*50)
    print("Available models:", ", ".join(models.keys()))
    print("Type 'exit' to quit")

    while True:
        prompt = input("\nEnter prompt: ")
        if prompt.lower() == "exit":
            break

        length = input("Max length (default 100): ")
        try:
            max_length = int(length) if length else 100
        except:
            max_length = 100

        temp = input("Temperature (0.1-1.0, default 0.7): ")
        try:
            temperature = float(temp) if temp else 0.7
            temperature = max(0.1, min(1.0, temperature))
        except:
            temperature = 0.7

        print("\nGenerating text from all models...")
        for model_name, model in models.items():
            input_ids = tokenizer.encode(prompt, return_tensors="pt").to(device)
            output = model.generate(
                input_ids,
                max_length=max_length,
                temperature=temperature,
                top_p=0.9,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id
            )

            generated_text = tokenizer.decode(output[0], skip_special_tokens=True)

            print(f"\n{model_name.upper()} MODEL OUTPUT:")
            print(generated_text)

    print("Demo completed.")

# Run the interactive demo
interactive_demo()

"""Лора з адаптером"""

# Fine-Tuning a Pretrained LLM on Ukrainian Literature (Fixed for latest PEFT)
# =================================================

# Install required packages
!pip install -q transformers datasets evaluate nltk tqdm matplotlib pandas
!pip install -q peft  # Використовуємо найновішу версію PEFT

import torch
import numpy as np
import pandas as pd
import os
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling
)
from peft import (
    get_peft_model,
    LoraConfig,
    TaskType,
    PeftModel,
    PeftConfig
)
import nltk
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from tqdm import tqdm
import matplotlib.pyplot as plt
import time
import requests
from bs4 import BeautifulSoup
import re
import logging

# Set up logging to debug any issues
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Повне завантаження пакетів NLTK
nltk.download('punkt_tab')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
# Додатково завантажте інші необхідні ресурси
nltk.download('wordnet')

# Check for GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
print(f"GPU available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU name: {torch.cuda.get_device_name(0)}")

# Create directories
os.makedirs("data", exist_ok=True)
os.makedirs("models", exist_ok=True)
os.makedirs("results", exist_ok=True)

# Download and Prepare Dataset
def download_kobzar():
    """Download Taras Shevchenko's 'Kobzar' or create a sample"""
    print("Downloading/Creating Kobzar dataset...")

    # Sample fallback content
    sample = """
Думи мої, думи мої,
Лихо мені з вами!
Нащо стали на папері
Сумними рядами?..
Чом вас вітер не розвіяв
В степу, як пилину?
Чом вас лихо не приспало,
Як свою дитину?...

Бо вас лихо на світ на сміх породило,
Поливали сльози... чом не затопили?
Не винесли в море, не розмили в полі?..
Не питали б люде: що в мене болить?
Не питали б, за що проклинаю долю,
Чого нужу світом? «Нічого робить»,—
Не сказали б на сміх...

Думи мої, думи мої,
Квіти мої, діти!
Виростав вас, доглядав вас —
Де ж мені вас діти?..
В Україну ідіть, діти!
В нашу Україну,
Попідтинню, сиротами,
А я — тут загину.

Вітре буйний, вітре буйний!
Ти з морем говориш,
Збуди його, заграй ти з ним,
Спитай синє море.
Воно знає, де мій милий,
Бо його носило,
Воно скаже, синє море,
Де його поділо.
Коли милого втопило —
Розбий синє море;
Піду шукать миленького,
Втоплю своє горе,
Втоплю свою недоленьку,
Русалкою стану

Пошукаю в чорних хвилях,
На дно моря кану.
Найду його, пригорнуся,
На серці зомлію.
Тоді, хвиле, неси з милим,
Куди вітер віє!
Коли ж милий на тім боці,
Буйнесенький, знаєш,
Де він ходить, що він робить,
Ти з ним розмовляєш.
Коли плаче — то й я плачу,
Коли ні — співаю;
Коли ж згинув чорнобривий, —
То й я погибаю.

Тогді неси мою душу
Туди, де мій милий;
Червоною калиною
Постав на могилі.
Буде легше в чужім полі
Сироті лежати —
Буде над ним його мила
Квіткою стояти.
І квіткою й калиною
Цвісти над ним буду,
Щоб не пекло чуже сонце,
Не топтали люде

Я ввечері посумую,
А вранці поплачу.
Зійде сонце — утру сльози,
Ніхто й не побачить.
Вітре буйний, вітре буйний!
Ти з морем говориш,
Збуди його, заграй ти з ним,
Спитай синє море…

Сонце гріє, вітер віє
З поля на долину,
Над водою гне вербою
Червону калину;
На калині одиноке
Гніздечко гойдає, —
А де ж дівся соловейко?
Не питай, не знає.

Згадай лихо — та й байдуже…
Минулось… пропало…
Згадай добре — серце в'яне:
Чому не осталось?
Отож гляну та згадаю:
Було, як смеркає,
Защебече на калині —
Ніхто не минає.
Чи багатий, кого доля,
Як мати дитину,
Убирає, доглядає, —
Не мине калину.
Чи сирота, що до світа
Встає працювати,
Опиниться, послухає;
Мов батько та мати
Розпитують, розмовляють, —
Серце б'ється, любо…

І світ божий як великдень,
І люди як люди.
Чи дівчина, що милого
Щодень виглядає,
В'яне, сохне сиротою,
Де дітись не знає;
Піде на шлях подивитись,
Поплакати в лози, —
Защебече соловейко —
Сохнуть дрібні сльози.
Послухає, усміхнеться,
Піде темним гаєм…
Ніби з милим розмовляла…

А він, знай, співає,
Та дрібно, та рівно, як бога благає,
Поки вийде злодій на шлях погулять
З ножем у халайві, — піде руна гаєм,
Піде та замовкне — нащо щебетать?
Запеклую душу злодія не спинить,
Тільки стратить голос, добру не навчить.
Нехай же лютує, поки сам загине,
Поки безголов'я ворон прокричить.
Засне долина.
    """

    # Try to download online content first
    try:
        url = "https://www.ukrlib.com.ua/books/printit.php?tid=27"
        response = requests.get(url)

        if response.status_code == 200:
            soup = BeautifulSoup(response.content, 'html.parser')

            # Find main content
            content = soup.find('div', class_='main-content')
            if content:
                # Extract poems
                poems_text = []
                poems = content.find_all('p')

                for poem in poems:
                    text = poem.get_text().strip()
                    if text and len(text) > 10:  # Filter out empty or very short lines
                        poems_text.append(text)

                # Save to file
                output_file = "data/kobzar.txt"
                with open(output_file, 'w', encoding='utf-8') as f:
                    f.write("\n\n".join(poems_text))

                print(f"Kobzar saved to {output_file}")
                print(f"Downloaded {len(poems_text)} poems")
                return output_file
    except Exception as e:
        print(f"Error downloading Kobzar: {e}")

    # Use sample if download fails
    print("Using sample Kobzar content")
    output_file = "data/kobzar_sample.txt"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(sample)

    print(f"Sample Kobzar saved to {output_file}")
    return output_file

def prepare_dataset(input_file, output_file=None, min_length=50):
    """Prepare dataset for fine-tuning"""
    if output_file is None:
        output_file = f"{input_file.rsplit('.', 1)[0]}_prepared.txt"

    # Read the file
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Split into sections
    sections = re.split(r'\n\s*\n', content)
    filtered_sections = [section.strip() for section in sections if len(section.strip()) >= min_length]

    print(f"Found {len(filtered_sections)} sections (min length: {min_length})")

    # Write prepared dataset
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("\n\n".join(filtered_sections))

    print(f"Prepared dataset saved to {output_file}")
    return output_file

# Download and prepare dataset
kobzar_file = download_kobzar()
prepared_file = prepare_dataset(kobzar_file)

# Define Fine-Tuning Functions
def load_dataset_from_file(file_path):
    """Load dataset from a text file"""
    with open(file_path, 'r', encoding='utf-8') as f:
        text = f.read()

    # Split into sections
    sections = text.split('\n\n')
    sections = [section.strip() for section in sections if len(section.strip()) > 50]

    # Create dataset
    dataset = Dataset.from_dict({
        'text': sections
    })

    print(f"Created dataset with {len(dataset)} entries")
    return dataset

def evaluate_stylistic_alignment(original_texts, generated_texts):
    """Evaluate stylistic alignment between original and generated texts"""
    # Average sentence length
    def avg_sentence_length(text):
        sentences = nltk.sent_tokenize(text)
        if not sentences:
            return 0
        return sum(len(nltk.word_tokenize(sentence)) for sentence in sentences) / len(sentences)

    original_avg_sent_len = [avg_sentence_length(text) for text in original_texts]
    generated_avg_sent_len = [avg_sentence_length(text) for text in generated_texts]

    sent_len_similarity = 1 - abs(np.mean(original_avg_sent_len) - np.mean(generated_avg_sent_len)) / max(np.mean(original_avg_sent_len), 1)

    # Vocabulary overlap
    def vocab_overlap(text1, text2):
        words1 = set(nltk.word_tokenize(text1.lower()))
        words2 = set(nltk.word_tokenize(text2.lower()))
        intersection = words1.intersection(words2)
        union = words1.union(words2)
        return len(intersection) / len(union) if union else 0

    vocab_similarities = [vocab_overlap(orig, gen) for orig, gen in zip(original_texts, generated_texts)]
    avg_vocab_similarity = np.mean(vocab_similarities)

    # Return composite score
    return (sent_len_similarity + avg_vocab_similarity) / 2

def generate_text(model, tokenizer, prompt, max_new_tokens=100):
    """Generate text using the fine-tuned model"""
    input_ids = tokenizer.encode(prompt, return_tensors="pt").to(device)

    # Generate text using max_new_tokens
    output = model.generate(
        input_ids,
        max_new_tokens=max_new_tokens,  # Using max_new_tokens instead of max_length
        num_return_sequences=1,
        temperature=0.7,
        top_p=0.9,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id
    )

    generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
    return generated_text

# Run Fine-Tuning Comparison
# Model and dataset settings
model_name = "gpt2"  # Base model
dataset_path = prepared_file  # Prepared dataset
output_dir = "results"
methods = ["lora", "adapter_custom"]  # Using custom adapter instead of the standard adapter

# Load tokenizer
print(f"Loading tokenizer: {model_name}")
tokenizer = AutoTokenizer.from_pretrained(model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# Load dataset
print(f"Loading dataset from {dataset_path}")
dataset = load_dataset_from_file(dataset_path)

# Split dataset
dataset = dataset.train_test_split(test_size=0.1, seed=42)
print(f"Train: {len(dataset['train'])} examples")
print(f"Test: {len(dataset['test'])} examples")

# Tokenization function
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=256,  # Reduced for Colab
        return_special_tokens_mask=True
    )

# Tokenize dataset
print("Tokenizing dataset...")
tokenized_datasets = dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=["text"]
)

# Create test prompts
test_samples = dataset['test'].select(range(min(5, len(dataset['test']))))
test_prompts = []

for text in test_samples:
    words = text['text'].split()
    if len(words) >= 20:
        prompt = " ".join(words[:20])
    else:
        prompt = " ".join(words[:max(3, len(words)//3)])
    test_prompts.append(prompt)

# Storage for results
results = {
    "Model": [],
    "Perplexity": [],
    "BLEU Score": [],
    "Stylistic Alignment": [],
    "Training Time (s)": [],
    "Trainable Parameters": []
}

models = {}
generated_texts = {}

# Data collator
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

# Common training arguments
common_args = {
    "num_train_epochs": 3,
    "per_device_train_batch_size": 2,
    "per_device_eval_batch_size": 2,
    "logging_dir": "./logs",
    "logging_steps": 50,
    "weight_decay": 0.01,
    "fp16": torch.cuda.is_available(),
    "save_steps": 100,
    "eval_steps": 100
}

# For calculating BLEU
smoother = SmoothingFunction().method1

# Run selected methods
for method in methods:
    if method == "lora":
        print("\n" + "="*50)
        print("Running LoRA Fine-tuning")
        print("="*50)

        # Load model
        base_model = AutoModelForCausalLM.from_pretrained(model_name)

        # Configure LoRA
        lora_config = LoraConfig(
            task_type=TaskType.CAUSAL_LM,
            r=8,  # Rank
            lora_alpha=32,
            lora_dropout=0.1,
            target_modules=["c_attn", "c_proj"] if "gpt2" in model_name.lower() else ["q_proj", "v_proj"],
        )

        # Get LoRA model
        lora_model = get_peft_model(base_model, lora_config)
        lora_model.to(device)

        trainable_params = sum(p.numel() for p in lora_model.parameters() if p.requires_grad)
        all_params = sum(p.numel() for p in lora_model.parameters())
        print(f"Trainable parameters: {trainable_params:,} ({trainable_params/all_params:.2%} of total)")

        lora_args = TrainingArguments(
            output_dir=f"{output_dir}/lora",
            overwrite_output_dir=True,
            num_train_epochs=3,
            per_device_train_batch_size=2,
            per_device_eval_batch_size=2,
            eval_strategy="epoch",  # Changed from evaluation_strategy
            save_strategy="epoch",  # Also changed for consistency
            logging_dir="./logs",
            logging_steps=50,
            weight_decay=0.01,
            fp16=torch.cuda.is_available(),
            load_best_model_at_end=True,
        )

        # Trainer
        lora_trainer = Trainer(
            model=lora_model,
            args=lora_args,
            train_dataset=tokenized_datasets["train"],
            eval_dataset=tokenized_datasets["test"],
            data_collator=data_collator,
        )

        # Train
        print("Starting LoRA fine-tuning...")
        start_time = time.time()
        lora_trainer.train()
        lora_time = time.time() - start_time
        print(f"Training completed in {lora_time:.2f} seconds")

        # Save model
        lora_trainer.save_model(f"{output_dir}/lora")

        # Calculate perplexity
        eval_results = lora_trainer.evaluate()
        lora_perplexity = torch.exp(torch.tensor(eval_results["eval_loss"])).item()
        print(f"LoRA model perplexity: {lora_perplexity:.2f}")

        # Generate text
        lora_generated = []
        for prompt in tqdm(test_prompts):
            generated = generate_text(lora_model, tokenizer, prompt)
            lora_generated.append(generated)

        # Calculate BLEU
        lora_bleu_scores = []
        for ref, gen in zip([sample['text'] for sample in test_samples], lora_generated):
            ref_tokens = nltk.word_tokenize(ref.lower())
            gen_tokens = nltk.word_tokenize(gen.lower())
            bleu = sentence_bleu([ref_tokens], gen_tokens, smoothing_function=smoother)
            lora_bleu_scores.append(bleu)

        lora_bleu = np.mean(lora_bleu_scores)
        print(f"LoRA model BLEU score: {lora_bleu:.4f}")

        # Stylistic alignment
        lora_style = evaluate_stylistic_alignment(
            [sample['text'] for sample in test_samples],
            lora_generated
        )
        print(f"LoRA model stylistic alignment: {lora_style:.4f}")

        # Store results
        results["Model"].append("LoRA")
        results["Perplexity"].append(lora_perplexity)
        results["BLEU Score"].append(lora_bleu)
        results["Stylistic Alignment"].append(lora_style)
        results["Training Time (s)"].append(lora_time)
        results["Trainable Parameters"].append(trainable_params)

        models["lora"] = lora_model
        generated_texts["lora"] = lora_generated

    elif method == "adapter_custom":
        print("\n" + "="*50)
        print("Застосування Custom Adapter методу")
        print("="*50)

        try:
            # Завантажуємо модель
            base_model = AutoModelForCausalLM.from_pretrained(model_name)
            logger.info("Базову модель завантажено успішно")

            # Замість AdapterConfig ми реалізуємо власну версію адаптерів
            # Ми можемо використовувати LoraConfig з певними модифікаціями для емуляції Adapter
            # У LoRA параметр r вказує ранг матриць, подібно до bottleneck_dim в Adapter

            adapter_lora_config = LoraConfig(
                task_type=TaskType.CAUSAL_LM,
                r=32,  # Відповідає adapter_size в AdapterConfig
                lora_alpha=16,
                lora_dropout=0.1,
                # Застосування до всіх модулів attention і MLP для емуляції adapter
                target_modules=["c_attn", "c_proj", "c_fc"] if "gpt2" in model_name.lower() else ["q_proj", "v_proj", "k_proj", "out_proj", "fc1", "fc2"],
                bias="none",
                modules_to_save=None,  # Не зберігаємо жодні модулі повністю
            )
            logger.info("Конфігурацію Custom Adapter створено успішно")

            # Отримуємо Custom Adapter модель
            adapter_model = get_peft_model(base_model, adapter_lora_config)
            adapter_model.to(device)
            logger.info("Custom Adapter модель створено успішно")

            trainable_params = sum(p.numel() for p in adapter_model.parameters() if p.requires_grad)
            all_params = sum(p.numel() for p in adapter_model.parameters())
            print(f"Навчальні параметри: {trainable_params:,} ({trainable_params/all_params:.2%} від загальної кількості)")

            # Оптимізовані параметри навчання для Custom Adapter
            adapter_args = TrainingArguments(
                output_dir=f"{output_dir}/adapter_custom",
                overwrite_output_dir=True,
                num_train_epochs=4,
                per_device_train_batch_size=2,
                per_device_eval_batch_size=2,
                logging_dir="./logs",
                logging_steps=10,
                save_steps=50,
                eval_steps=50,
                weight_decay=0.01,
                learning_rate=2e-4,
                fp16=torch.cuda.is_available(),
                eval_strategy="steps",   # Changed from evaluation_strategy
                save_strategy="steps"    # For consistency
            )

            # Тренер
            adapter_trainer = Trainer(
                model=adapter_model,
                args=adapter_args,
                train_dataset=tokenized_datasets["train"],
                eval_dataset=tokenized_datasets["test"],
                data_collator=data_collator,
            )

            # Навчання
            print("Початок навчання з Custom Adapter методом...")
            start_time = time.time()
            adapter_trainer.train()
            adapter_time = time.time() - start_time
            print(f"Навчання завершено за {adapter_time:.2f} секунд")

            # Збереження моделі
            adapter_trainer.save_model(f"{output_dir}/adapter_custom")

            # Обчислення перплексії
            eval_results = adapter_trainer.evaluate()
            adapter_perplexity = torch.exp(torch.tensor(eval_results["eval_loss"])).item()
            print(f"Custom Adapter перплексія моделі: {adapter_perplexity:.2f}")

            # Генерація тексту з оптимізованими параметрами для української поезії
            adapter_generated = []
            for prompt in tqdm(test_prompts):
                input_ids = tokenizer.encode(prompt, return_tensors="pt").to(device)
                output = adapter_model.generate(
                    input_ids,
                    max_new_tokens=100,
                    num_return_sequences=1,
                    temperature=0.4,  # Нижча температура для більш консервативної генерації
                    top_k=40,
                    repetition_penalty=1.3,  # Штраф за повторення
                    do_sample=True,
                    pad_token_id=tokenizer.eos_token_id,
                    no_repeat_ngram_size=3,  # Запобігає повторенню триграм
                )
                generated_text = tokenizer.decode(output[0], skip_special_tokens=True)
                adapter_generated.append(generated_text)

            # Оцінювання BLEU
            adapter_bleu_scores = []
            for ref, gen in zip([sample['text'] for sample in test_samples], adapter_generated):
                ref_tokens = nltk.word_tokenize(ref.lower())
                gen_tokens = nltk.word_tokenize(gen.lower())

                # Знаходимо перші українські слова після промпту
                prompt_len = len(nltk.word_tokenize(test_prompts[adapter_bleu_scores.__len__()].lower()))
                relevant_gen_tokens = gen_tokens[prompt_len:prompt_len+20]  # Беремо 20 токенів після промпту

                if relevant_gen_tokens:
                    bleu = sentence_bleu([ref_tokens], relevant_gen_tokens, smoothing_function=smoother)
                else:
                    bleu = 0

                adapter_bleu_scores.append(bleu)

            adapter_bleu = np.mean(adapter_bleu_scores)
            print(f"Custom Adapter модель BLEU score: {adapter_bleu:.4f}")

            # Оцінка стилістичної відповідності
            adapter_style = evaluate_stylistic_alignment(
                [sample['text'] for sample in test_samples],
                adapter_generated
            )
            print(f"Custom Adapter модель stylistic alignment: {adapter_style:.4f}")

            # Зберігаємо результати
            results["Model"].append("Custom Adapter")
            results["Perplexity"].append(adapter_perplexity)
            results["BLEU Score"].append(adapter_bleu)
            results["Stylistic Alignment"].append(adapter_style)
            results["Training Time (s)"].append(adapter_time)
            results["Trainable Parameters"].append(trainable_params)

            models["adapter_custom"] = adapter_model
            generated_texts["adapter_custom"] = adapter_generated

        except Exception as e:
            logger.error(f"Критична помилка при роботі з Custom Adapter: {e}")
            print(f"Виникла помилка при роботі з Custom Adapter методом: {e}")
            print("Спробуйте оновити бібліотеку PEFT або використайте альтернативний метод.")

# Results table
results_df = pd.DataFrame(results)
print("\nResults Summary:")
print(results_df)

# Save results to CSV
results_df.to_csv(f"{output_dir}/comparison_results.csv", index=False)

# Plot results
def plot_metrics(results_df, output_file="results_comparison.png"):
    """Plot comparison of fine-tuning methods"""
    metrics = ["Perplexity", "BLEU Score", "Stylistic Alignment", "Training Time (s)"]

    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    axes = axes.flatten()

    fig.suptitle("Fine-Tuning Methods Comparison", fontsize=16)

    for i, metric in enumerate(metrics):
        ax = axes[i]
        bars = ax.bar(results_df["Model"], results_df[metric])
        ax.set_title(metric, fontsize=14)
        ax.set_ylabel(metric)

        # Add values on bars
        for bar in bars:
            height = bar.get_height()
            ax.annotate(f'{height:.4f}',
                       xy=(bar.get_x() + bar.get_width() / 2, height),
                       xytext=(0, 3),
                       textcoords="offset points",
                       ha='center', va='bottom',
                       fontsize=10)

    plt.tight_layout()
    plt.subplots_adjust(top=0.9)
    plt.savefig(output_file)
    plt.show()  # Display in Colab

# Plot the results
plot_metrics(results_df, f"{output_dir}/comparison_plot.png")

# Print examples
print("\nText Generation Examples:")
for i in range(min(2, len(test_samples))):  # Limit to 2 examples or less if fewer samples
    sample = test_samples[i]
    print("-" * 80)
    # Make sure sample is a dictionary and has a 'text' key
    if isinstance(sample, dict) and 'text' in sample:
        print(f"ORIGINAL TEXT:\n{sample['text'][:150]}...\n")
    else:
        print(f"ORIGINAL TEXT:\n{str(sample)[:150]}...\n")

    print(f"PROMPT: {test_prompts[i]}\n")

    for model_name, texts in generated_texts.items():
        if i < len(texts):
            print(f"{model_name.upper()} MODEL:\n{texts[i][:150]}...\n")

    print("-" * 80)

# Interactive Text Generation Demo
def interactive_demo():
    """Interactive demo for testing fine-tuned models"""
    print("\n" + "="*50)
    print("INTERACTIVE DEMO")
    print("="*50)
    print("Available models:", ", ".join(models.keys()))
    print("Type 'exit' to quit")

    while True:
        prompt = input("\nEnter prompt: ")
        if prompt.lower() == "exit":
            break

        length = input("Max length (default 100): ")
        try:
            max_length = int(length) if length else 100
        except:
            max_length = 100

        temp = input("Temperature (0.1-1.0, default 0.7): ")
        try:
            temperature = float(temp) if temp else 0.7
            temperature = max(0.1, min(1.0, temperature))
        except:
            temperature = 0.7

        print("\nGenerating text from all models...")
        for model_name, model in models.items():
            input_ids = tokenizer.encode(prompt, return_tensors="pt").to(device)
            output = model.generate(
                input_ids,
                max_new_tokens=max_length,
                temperature=temperature,
                top_p=0.9,
                do_sample=True,
                pad_token_id=tokenizer.eos_token_id
            )

            generated_text = tokenizer.decode(output[0], skip_special_tokens=True)

            print(f"\n{model_name.upper()} MODEL OUTPUT:")
            print(generated_text)

    print("Demo completed.")

# Run the interactive demo
interactive_demo()