# -*- coding: utf-8 -*-
"""NLP 4 v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5xhUHOHdr2XU0B2TWkXIPSglcqWGVe8
"""

# -*- coding: utf-8 -*-

!pip install datasets sentence-transformers faiss-cpu transformers

from datasets import load_dataset

dataset = load_dataset("wikipedia", "20220301.en", split="train[:500]")

print(dataset)

print(dataset[0])

# Вивід перших прикладів
print("📄 Приклади текстів:\n")
for i in range(3):
    print(f"--- Text {i+1} ---")
    print(dataset[i])
    print('')

def simple_sentence_tokenize(text):
    sentences = text.replace('?', '.').replace('!', '.').split('.')
    return [s.strip() for s in sentences if len(s.strip().split()) > 3]

chunks = []

for article in dataset:
    sentences = simple_sentence_tokenize(article["text"])
    for i in range(0, len(sentences), 3):
        chunk = " ".join(sentences[i:i+3])
        if len(chunk.strip().split()) > 20:
            chunks.append(chunk.strip())

print(f"Усього отримано {len(chunks)} фрагментів")

# Вивід перших прикладів
print("📄 Приклади фрагментів:\n")
for i in range(10):
    print(f"--- Fragment {i+1} ---\n{chunks[i]}\n")

# Статистика по довжині фрагментів
import matplotlib.pyplot as plt
chunk_lengths = [len(c.split()) for c in chunks]

plt.figure(figsize=(10, 6))
plt.hist(chunk_lengths, bins=40, edgecolor='black')
plt.title("Розподіл довжини фрагментів (у словах)", fontsize=14)
plt.xlabel("Кількість слів", fontsize=12)
plt.ylabel("Кількість фрагментів", fontsize=12)
plt.grid(True)
plt.tight_layout()
plt.show()

from sentence_transformers import SentenceTransformer
import numpy as np

# Завантаження моделі (заміна на новішу модель)
embed_model = SentenceTransformer('intfloat/multilingual-e5-large')

# Генерація embeddings
embeddings = embed_model.encode(chunks, show_progress_bar=True, convert_to_numpy=True)

# Перевірка розмірів
print(f"Embeddings shape: {embeddings.shape}")

import faiss

# Створення FAISS індексу (розмірність має відповідати розмірності embeddings)
index = faiss.IndexFlatL2(embeddings.shape[1])
index.add(embeddings)

print(f"Векторна база створена: {index.ntotal} фрагментів проіндексовано")

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# Приклад: якщо вже є готові chunks та індекс
query = "What is Quantum computing?"

# Генерація embedding для запиту
query_embedding = embed_model.encode([query], convert_to_numpy=True)

# Пошук найближчих фрагментів
top_k = 5
D, I = index.search(query_embedding, top_k)

# Вивід результатів
print(f"🔍 Результати пошуку для запиту: \"{query}\"\n")
for rank, idx in enumerate(I[0]):
    print(f"🔹 Rank {rank+1}:")
    print(chunks[idx][:300], "\n")

"""https://huggingface.co/mistralai/Mistral-7B-v0.1"""

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
from huggingface_hub import login

login(token="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")

model_name = "mistralai/Mistral-7B-v0.1"

# Завантаження токенізатора та моделі
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

def retrieve_chunks(query, embed_model, index, chunks, top_k=5):
    query_embedding = embed_model.encode([query], convert_to_numpy=True)
    _, I = index.search(query_embedding, top_k)
    return [chunks[i] for i in I[0]]

def build_prompt(query, retrieved_chunks):
    context = "\n\n".join(retrieved_chunks)
    return f"""You are a helpful assistant. Use the context to answer the question concisely and directly. Do NOT repeat the context and question.

'''Context:
{context}

Answer the question: {query}'''

Answer:"""

def generate_answer(prompt, tokenizer, model, max_new_tokens=200):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            temperature=0.7,
            top_p=0.95
        )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

def extract_direct_answer(raw_output):
    parts = raw_output.split("Answer:")
    return parts[-1].strip() if len(parts) > 1 else raw_output.strip()

query = "What is Quantum computing?"

# 1. Витяг з FAISS
retrieved = retrieve_chunks(query, embed_model, index, chunks, top_k=5)

# 2. Побудова промпта
prompt = build_prompt(query, retrieved)
print("🔍 Prompt (обрізаний):\n", prompt)
# 3. Генерація з Mistral
answer = generate_answer(prompt, tokenizer, model)
clean_answer = extract_direct_answer(answer)

print('_______________________________________')
print("\n💬 Відповідь від Mistral:\n", clean_answer)

from sentence_transformers import util

# Функція: перевірка чи є збіг по gold answer
def is_answer_correct(generated_answer, gold_answers):
    generated_answer = generated_answer.lower()
    return any(
        gold.lower() in generated_answer or generated_answer in gold.lower()
        for gold in gold_answers
    )

def is_answer_semantically_correct(generated_answer, gold_answers, embed_model, threshold=0.75):
    gen_emb = embed_model.encode(generated_answer, convert_to_tensor=True)
    for gold in gold_answers:
        gold_emb = embed_model.encode(gold, convert_to_tensor=True)
        sim = util.cos_sim(gen_emb, gold_emb).item()
        if sim >= threshold:
            return True
    return False

def evaluate_recall_at_k(test_queries, embed_model, index, chunks, tokenizer, model, k=5):
    hits = 0
    for i, (query, gold_answers) in enumerate(test_queries):
        print(f"Обробка запиту {i+1}/{len(test_queries)}: \"{query}\"")

        # 1. Витяг з бази
        retrieved = retrieve_chunks(query, embed_model, index, chunks, top_k=k)

        # 2. Формування промпта
        prompt = build_prompt(query, retrieved)

        # 3. Генерація
        raw_answer = generate_answer(prompt, tokenizer, model)
        clean_answer = extract_direct_answer(raw_answer)

        # 4. Семантична перевірка
        if is_answer_semantically_correct(clean_answer, gold_answers, embed_model):
            hits += 1
            print("Відповідь правильна")
        else:
            print("Відповідь НЕ знайдена")

        print(" Відповідь:\n", clean_answer[:300], "\n" + "-"*60)

    recall = hits / len(test_queries)
    print(f"\nRecall@{k}: {recall:.3f} ({hits}/{len(test_queries)})")
    return recall

test_queries = [
    (
        "What is Quantum computing?",
        ["Quantum computing is a type of computation that harnesses quantum mechanical phenomena, such as superposition and entanglement, to perform operations on data."]
    ),
    (
        "What is Artificial Intelligence?",
        ["Artificial intelligence is intelligence demonstrated by machines, as opposed to natural intelligence displayed by animals including humans."]
    ),
    (
        "What is Blockchain technology?",
        ["Blockchain is a distributed ledger technology that enables secure, transparent and tamper-proof record keeping of transactions across a decentralized network."]
    ),
]

evaluate_recall_at_k(test_queries, embed_model, index, chunks, tokenizer, model, k=5)